  location=".platform.app.yaml"
  name: node-app

  type: nodejs:16

  disk: 512

  dependencies:
    nodejs:
      yarn: "*"

  hooks:
    build: |
      npm run setup-assets
      npm run build

  web:
    commands:
      start: "node index.js"